import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Miracle Inside",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ul className="navbar-nav ml-auto close-mobile-menu-hello">
       
      
            <li className="nav__item close-mobile-menu-hello">
              <Link href=""
                className="nav__item-link close-mobile-menu-hello"
              >
              
              </Link>
            </li>

        <li className="nav__item close-mobile-menu-hello">
          
          <a
            style={{ marginTop: "20px" }}
            href="https://miracleinside3d4dbabyscancentre.gettimely.com/Booking/Location/89781?mobile=True"
            className="btn btn__primary btn__rounded ml-30"
          >
            <span>Book Now</span>
          </a>
        </li>
      </ul> */}

        {children}
      </body>
    </html>
  );
}
